#cloud-config

write_files:
  - path: /var/docker/volumes/redis/keep
  - path: /etc/systemd/system/redis.service
    content: |
      [Unit]
      Description=Redis
      After=docker.service
      Requires=docker.service

      [Service]
      TimeoutStartSec=0
      ExecStartPre=-/usr/bin/docker kill redis
      ExecStartPre=-/usr/bin/docker rm redis
      ExecStartPre=/usr/bin/docker pull redis:3.2-alpine
      ExecStart=/usr/bin/docker run --name redis -v /var/docker/volumes/redis:/data -d redis:3.2-alpine redis-server --appendonly yes

      [Install]
      WantedBy=multi-user.target
  - path: var/docker/volumes/nginx/tictactoe.conf
    content: |
      upstream backend {
          server tictactoe:3000;
      }

      server {
          location tictactoe.homedir.eu/ {
              proxy_pass http://backend;
          }
      }
  - path: /etc/systemd/system/nginx.service
    content: |
      [Unit]
      Description=Nginx
      After=docker.service
      After=tic-tac-toe.service
      Requires=docker.service
      Requires=tic-tac-toe.service

      [Service]
      TimeoutStartSec=0
      ExecStartPre=-/usr/bin/docker kill nginx
      ExecStartPre=-/usr/bin/docker rm nginx
      ExecStartPre=/usr/bin/docker pull nginx:1.13.5
      ExecStart=/usr/bin/docker run --name nginx -p 80:80 -v /var/docker/volumes/nginx/tictactoe.conf:/etc/nginx/conf.d/tictactoe.conf:ro --link tictactoe -d nginx:1.13.5

      [Install]
      WantedBy=multi-user.target
  - path: /etc/systemd/system/tic-tac-toe.service
    content: |
      [Unit]
      Description=TicTacToe
      After=docker.service
      After=redis.service
      Requires=docker.service
      Requires=redis.service

      [Service]
      TimeoutStartSec=0
      ExecStartPre=-/usr/bin/docker kill tictactoe
      ExecStartPre=-/usr/bin/docker rm tictactoe
      ExecStartPre=/usr/bin/docker pull vipo/tic-tac-toe:latest
      ExecStart=/usr/bin/docker run --name tictactoe -p 3000:3000 -d --link redis vipo/tic-tac-toe:latest tic-tac-toe

      [Install]
      WantedBy=multi-user.target

coreos:
  units:
    - name: redis.service
      command: start
    - name: tic-tac-toe.service
      command: start
    - name: nginx.service
      command: start
